let a=30;
let b=10;
let c=a+b;
let d=a-b;
console.log(c);
console.log(d);
console.log(a*b);
console.log(a%b);
console.error("BOB IS HERE");
console.warn("BOB IS COMING");
let p=1;
let q=++p;
console.log(p);
console.log(q);